apiVersion: 1

datasources:
  # Prometheus data source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.55.1
      cacheLevel: 'High'
      incrementalQuerying: false
      exemplarTraceIdDestinations:
        - name: traceID
          url: http://localhost:16686/trace/$${__value.raw}

  # Loki data source for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - matcherRegex: 'trace_id=(\w+)'
          name: TraceID
          url: 'http://localhost:16686/trace/$${__value.raw}'

  # Postgres data source (optional for application metrics)
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    uid: postgres
    editable: false
    database: pdm_db
    user: admin
    secureJsonData:
      password: root
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
